# Generated by Django 5.1.3 on 2024-11-30 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hobbies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('was_accepted', models.BooleanField(default=False)),
                ('coins_spent', models.PositiveIntegerField(default=0)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
