# Generated by Django 5.1.3 on 2024-11-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='category',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='related_hobbies',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userhobby',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='hobbytasting',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='roulettehistory',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='roulettehistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userhobby',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='HobbyTasting',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='RouletteHistory',
        ),
        migrations.DeleteModel(
            name='UserHobby',
        ),
    ]
